---
#enter pc to med.cap.ru domain
#usage: ansible-playbook domain.yml --ask-vault-pass
- hosts: setup
  become: yes
  remote_user: asergeev
  gather_facts: yes
  any_errors_fatal: yes
  tasks:
  - name: add vars
    include_vars:
      file: astra.yml
  - name: join to ad
    shell: "echo -n {{ domain_password }} | sudo adcli join --verbose --domain {{ domain }} --domain-realm {{ domain|upper }} --domain-controller 192.168.92.3 --computer-ou OU=Компьютеры,OU=Yaltch-CRB,OU=CRB,OU=LPU,OU=MED,DC=med,DC=cap,DC=ru --login-type user --user {{ domain_admin }} --stdin-password --verbose"
    #args:
    #  stdin: "{{ domain_password }}\n"
    register: adcli_res
  - name: display adcli res
    debug:
      msg: "res: {{ adcli_res.rc }}; msg: {{ adcli_res }}"
  - name: add computer to ad
    shell: "echo {{ domain_password }} | sudo astra-ad-sssd-client -d {{ domain }} -u {{ domain_admin }} -n 192.168.92.2 -y -px"
    #args:
    #  stdin: "{{ domain_password }}\n"
    #cat /root/pass | sudo astra-ad-sssd-client -d domain.net -u admin -px -y
    register: sssd_res
  - name: display sssd res
    debug:
      msg: "res: {{ sssd_res.rc }}; msg: {{ sssd_res.stdout }}"
  - name: restart a pc #reboot command required ansible 2.7
    reboot:
...