---
# playbook for updating dr web
# usage: ansible-playbook drweb.yml
- hosts: ped
  become: true
  remote_user: asergeev
  gather_facts: true
  tasks:
    - name: Copy notify script for Astra
      ansible.builtin.copy:
        src: files/notify-all-astra.sh
        dest: /usr/bin/notify-all
        owner: root
        mode: '0700'
      when: ansible_distribution == "Astra Linux (Orel)"

    - name: Copy notify script for Ubuntu
      ansible.builtin.copy:
        src: files/notify-all-ubuntu.sh
        dest: /usr/bin/notify-all
        owner: root
        mode: '0700'
      when: ansible_distribution == "Ubuntu"

    - name: Check for existing drweb install
      ansible.builtin.stat:
        path: /opt/drweb.com/bin/drweb-ctl
      register: result1

    - name: Get current drweb version
      ansible.builtin.command: drweb-ctl -v
      register: curdrwebver
      when: "result1.stat.exists"
      failed_when: false
      changed_when: false
    - name: Print drweb version
      ansible.builtin.debug:
        msg: "{{ curdrwebver.stdout }}"


    - name: Stop to play
      when: "result1.stat.exists and curdrwebver.stdout and curdrwebver.stdout in 'drweb-ctl 11.1.11.2111261834'"
      block:
        - name: No update required
          ansible.builtin.debug:
            msg: "Nothing to upgrade, exiting"
        - name: End play
          ansible.builtin.meta: end_play

    - name: Continuing
      ansible.builtin.debug:
        msg: "Need to update drweb to 11.1.11"

    - name: Notify users to reboot
      ansible.builtin.command: /usr/bin/notify-all -t 60000 "Предупреждение" "Компьютер будет перезагружен через одну минуту для переустановки антивируса. Сохраните все документы"
      changed_when: false

    - name: Wait for users
      ansible.builtin.wait_for:
        timeout: 60
      delegate_to: localhost

    - name: Delete old drweb
      ansible.builtin.command: /opt/drweb.com/bin/remove.sh --non-interactive
      changed_when: false

    - name: Reboot really required?
      ansible.builtin.reboot:

    - name: Copy drweb license file
      ansible.builtin.copy:
        src: files/certificate.pem
        dest: /tmp/certificate.pem
        owner: root
        mode: '600'

    - name: Copy drweb installer file
      ansible.builtin.copy:
        src: files/drweb-workstations_11.1.3-2201141226+fstek~linux_amd64.run
        dest: /tmp/drweb-workstations_11.1.3-2201141226+fstek~linux_amd64.run
        owner: root
        mode: '0700'

    - name: Run drweb installer
      ansible.builtin.command: /tmp/drweb-workstations_11.1.3-2201141226+fstek~linux_amd64.run -- --non-interactive
      changed_when: false

    - name: Apply drweb license file
      ansible.builtin.command: drweb-ctl esconnect 192.168.92.41:2193 --Certificate /tmp/certificate.pem --Newbie
      register: result2
      failed_when: "result2.rc != 0 and result2.rc != 69"
      changed_when: false

    - name: Allow winemis to drweb
      ansible.builtin.command: drweb-ctl cfset linuxfirewall.excludedproc /opt/wine/bin/wineserver
      changed_when: false

    - name: Restart drweb service
      ansible.builtin.service:
        name: drweb-configd
        state: restarted

    - name: Notify users to complete
      ansible.builtin.command: /usr/bin/notify-all -t 60000 "Информация" "Антивирус переустановлен, необходима перезагрузка. После нее можете продолжить работу"
      changed_when: false

    - name: Reboot really required?
      ansible.builtin.reboot:
...
