---
#setup for ubuntu 20.04. pre-required nopasswd sudo
#usage: ansible-playbook ubuntu.yml --ask-pass --ask-vault-pass
- hosts: ubuntu
  become: yes
  remote_user: test

  tasks:
  - name: add vars
    include_vars:
      ubuntu.yml
  - name: proxy for wget #commented, cause no proxy req
    lineinfile:
      path: /etc/wgetrc
      line: "#use_proxy=yes\n#http_proxy=192.168.192.93:3128\n#https_proxy=192.168.192.93:3128"
  - name: sync time with hw clock
    shell: timedatectl set-local-rtc 1 --adjust-system-clock

  #hostname and ad
  - block:
    - name: set a new hostname
      hostname:
        name: "{{ hostname }}.{{ domain }}"  
    - name: set hostname in /etc/hosts
      lineinfile:
        path: "/etc/hosts"
        regexp: "^127.0.1.1"
        line: "127.0.1.1  {{hostname}}.{{ domain }} {{ hostname }}"

    - name: disable auto upgrades
      copy:
        src: files/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: '0644'

    - name: first reboot
      reboot:

    - name: add to domain
      shell: "echo {{ domain_password }} | realm join --verbose --user={{ domain_admin }} --computer-ou=OU=Компьютеры,OU=Yaltch-CRB,OU=CRB,OU=LPU,OU=MED,DC=med,DC=cap,DC=ru {{ domain }} --install=/"
      register: join_res
    - name: display sssd res
      debug:
        msg: "res: {{ join_res.rc }}; msg: {{ join_res.stdout }}"
    - name: copy realmd
      copy:
        src: files/realmd.conf
        dest: /etc/realmd.conf
    - name: copy common-session
      copy:
        src: files/common-session
        dest: /etc/pam.d/common-session
    - name: copy sssd.conf
      copy:
        src: files/sssd.conf
        dest: /etc/sssd/sssd.conf

    - name: second reboot
      reboot:

  - block:
    - name: install necessary packages
      apt:
        name:
          - mc
          - sudo
          - htop
          - iotop
          - lm-sensors
          - python-apt
          - ufw
          - libnss3-tools
          - cifs-utils
          - nfs-common
          - pcscd
          - remmina
          - tmux
        state: present
    - name: remove ippusbxd
      apt:
        name: ippusbxd
        state: absent
        purge: yes

  - block:
    #work with users here
    - name: add admin user
      user:
        name: "{{ user1 }}"
        comment: "{{ username1 }}"
        shell: "/bin/bash"
        groups: sudo, lpadmin
        append: yes
        password: "{{ password1 }}"
    - name: add doctor user
      user:
        name: "{{ user2 }}"
        comment: "{{ username2 }}"
        shell: "/bin/bash"
        password: "{{ password2 }}"
    - name: add ssh key for admin
      authorized_key:
          user: "{{ user1 }}"
          key: "{{ lookup('file', 'files/150.pub') }}"
    - name: passwordless sudo for admin
      lineinfile:
        dest: "/etc/sudoers"
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"

    #chrome
  - name: copy chrome
    copy:
      src: files/google-chrome-stable_current_amd64.deb
      dest: /tmp/google-chrome-stable_current_amd64.deb
  - name: install chrome
    apt: deb=/tmp/google-chrome-stable_current_amd64.deb
  - name: remove chrome installer
    file:
      path: /tmp/google-chrome-stable_current_amd64.deb
      state: absent
  #rutoken
  - name: copy rutoken
    copy:
      src: files/libnpRutokenPlugin.deb
      dest: /tmp/libnpRutokenPlugin.deb
  - name: install rutoken
    apt: deb=/tmp/libnpRutokenPlugin.deb
  - name: remove rutoken installer
    file:
      path: /tmp/libnpRutokenPlugin.deb
      state: absent
  #russian cert
  - name: copy russian root cert
    copy:
      src: files/russian_trust_root_ca.crt
      dest: /usr/local/share/ca-certificates/russian_trust_root_ca.crt
      mode: '0755'
  - name: trust russian root cert
    shell: update-ca-certificates

  - block: #dr web
    - name: copy dr web license file
      copy:
        src: files/certificate.pem
        dest: /home/{{ user1 }}/certificate.pem
    - name: activate dr web
      shell: drweb-ctl esconnect 192.168.92.41:2193 --Certificate /home/{{ user1 }}/certificate.pem --Newbie
      ignore_errors: yes
  
  - block: # vipnet cfg
    - name: iptables off
      lineinfile:
        dest: "/etc/vipnet.conf"
        regexp: ";iptables=off"
        line: "iptables=off"
    - name: change dns
      lineinfile:
        dest: "/etc/vipnet.conf"
        regexp: "trusted=8.8.8.8"
        line: "trusted=192.168.92.3"

  - block: # disabling proxy everythere
    - name: for apt
      shell: mv /etc/apt/apt.conf /etc/apt/apt.conf.bak
    - name: for env
      shell: mv /etc/environment /etc/environment.bak
    - name: for proxy.sh
      shell: mv /etc/profile.d/proxy.sh /etc/profile.d/proxy.sh.bak
  #must be changed
  - name: egisz and esia
    lineinfile:
      dest: /etc/hosts
      line: "46.61.237.65 ia.egisz.rosminzdrav.ru\n185.194.33.90 vaccine.egisz.rosminzdrav.ru\n109.207.2.205 esia.gosuslugi.ru\n"

  - name: cups config
    copy:
      src: files/cupsd_ubuntu.conf
      dest: /etc/cups/cupsd.conf

  - name: update wine
    shell: curl -fsSL https://misupd.med.cap.ru/files/reinstall.sh | sudo -E bash -

  #ssh setup. do not restart sshd
  - name: change ssh port
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^#Port 22"
      line: "Port 225"
  - name: change ssh auth
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^#PasswordAuthentication yes"
      line: "PasswordAuthentication no"
  - name: disallow ssh for root
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^#PermitRootLogin yes"
      line: "PermitRootLogin no"

  - block: #firewall
    - name: deny incoming
      shell: ufw default deny incoming
    - name: allow outgoing
      shell: ufw default allow outgoing
    - name: allow ssh
      shell: ufw allow 225
    - name: allow cups
      shell: ufw allow 631
    - name: allow vnc
      shell: ufw allow 5900
    - name: enable fw
      shell: ufw --force enable

  - name: restart a pc
    reboot:
...