# for setup zabbix client and other stuff for astra2.12 and ubuntu 20.04
# place zabbix_agentd.conf to files dir.
# exec b4 run: ansible-galaxy collection install community.general
# run: ansible-playbook zabbix.yml
- hosts: setup
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Print release
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Download zabbix-agent for ubuntu
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: Download zabbix repo locally for Ubuntu
          ansible.builtin.get_url:
            url: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-1%2Bubuntu20.04_all.deb
            dest: files/zabbix-release_6.2-1+ubuntu20.04_all.deb
            mode: '0444'
          environment:
            https_proxy: "http://192.168.192.93:3128"
          delegate_to: 127.0.0.1
          run_once: true

        - name: Copy zabbix repo
          ansible.builtin.copy:
            src: files/zabbix-release_6.2-1+ubuntu20.04_all.deb
            dest: /tmp/zabbix-release.deb
            mode: '0444'

    - name: Download zabbix-agent for astra
      when: ansible_distribution == 'Astra Linux (Orel)'
      block:
        - name: Download zabbix repo locally for Astra
          ansible.builtin.get_url:
            url: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-3+debian9_all.deb
            dest: files/zabbix-release_6.0-3+debian9_all.deb
            mode: '0444'
          environment:
            https_proxy: "http://192.168.192.93:3128"
          delegate_to: 127.0.0.1
          run_once: true
        - name: Copy zabbix repo
          ansible.builtin.copy:
            src: files/zabbix-release_6.0-3+debian9_all.deb
            dest: /tmp/zabbix-release.deb
            mode: '0444'

    - name: Install zabbix repo
      ansible.builtin.apt:
        deb: /tmp/zabbix-release.deb
    - name: Remove zabbix installer
      ansible.builtin.file:
        path: /tmp/zabbix-release.deb
        state: absent
    - name: Https -> http in zabbix plugin repo list
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/zabbix-agent2-plugins.list
        regexp: 'https'
        replace: http
    - name: Https -> http in zabbix repo list
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/zabbix.list
        regexp: 'https'
        replace: http
    - name: Install zabbix agent and etc
      ansible.builtin.apt:
        name:
          - zabbix-agent2
          - inxi
          - hwinfo
        state: present
        update_cache: true

    # configs
    - name: Original config exists?
      ansible.builtin.stat:
        path: /etc/zabbix/zabbix_agent2.conf.bak
      register: old_config
    - name: Backup zabbix config
      ansible.builtin.copy:
        remote_src: true
        src: /etc/zabbix/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf.bak
        mode: '0600'
      when: not old_config.stat.exists
    - name: Copy zabbix config
      ansible.builtin.copy:
        src: files/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agent2.conf
        mode: '0600'

    - name: Enable & start zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: true
        state: started
    - name: Edit sudoers
      community.general.sudoers:
        name: zabbix
        user: zabbix
        runas: root
        commands:
          - /sbin/hwinfo
          - /usr/sbin/hwinfo
          - /opt/secretnet/bin/snlicensectl
        nopassword: true
...
