#https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-3+debian9_all.deb
#for setup zabbix client and other stuff
#place zabbix_agentd.conf to files dir.
#exec b4 run: ansible-galaxy collection install community.general
#run: ansible-playbook zabbix.yml
- hosts: virt
  become: yes
  gather_facts: yes

  tasks:
  - name: download zabbix-agent local
    get_url:
      url: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-3+debian9_all.deb
      dest: files/zabbix-release_6.0-3+debian9_all.deb
    environment:
      https_proxy: "http://192.168.192.93:3128"
    delegate_to: 127.0.0.1
    run_once: yes

  - name: copy zabbix
    copy:
      src: files/zabbix-release_6.0-3+debian9_all.deb
      dest: /tmp/zabbix-release_6.0-3+debian9_all.deb
  - name: install zabbix repo
    apt:
      deb: /tmp/zabbix-release_6.0-3+debian9_all.deb
  - name: remove zabbix installer
    file:
      path: /tmp/zabbix-release_6.0-3+debian9_all.deb
      state: absent
  - name: https -> http in zabbix plugin repo list
    replace:
      path: /etc/apt/sources.list.d/zabbix-agent2-plugins.list
      regexp: 'https'
      replace: http

  - name: https -> http in zabbix repo list
    replace:
      path: /etc/apt/sources.list.d/zabbix.list
      regexp: 'https'
      replace: http  
  
  - name: install zabbix agent and etc
    apt: 
      name:
        - zabbix-agent2
        - inxi
        - hwinfo
      state: present
      update_cache: yes

  - name: backup zabbix config
    copy:
      remote_src: yes
      src: /etc/zabbix/zabbix_agent2.conf
      dest: /etc/zabbix/zabbix_agent2.conf.bak
  - name: copy zabbix config
    copy:
      src: files/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agent2.conf
  
  - name: enable & start zabbix-agent
    service:
      name: zabbix-agent2
      enabled: yes
      state: started
    #('/etc/sudoers.d')
  - name: edit sudoers 1
    community.general.sudoers:
      name: zabbix
      user: zabbix
      runas: root
      commands:
        - /sbin/hwinfo
        - /usr/sbin/hwinfo
        - /opt/secretnet/snlicensectl
      nopassword: yes
...